name:                lisp-formatter
version:             0.1.0.0
github:              "pe200012/lisp-formatter"
license:             BSD-3-Clause
author:              "pe200012"
maintainer:          "1326263755@qq.com"
copyright:           "2025 pe200012"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pe200012/lisp-formatter#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 2.0 && < 2.2
- megaparsec >= 9.0 && < 10
- optparse-applicative >= 0.16 && < 0.19
- dhall >= 1.40 && < 1.43
- directory >= 1.3 && < 1.4
- filepath >= 1.4 && < 1.5
- mtl >= 2.3 && < 2.5
- recursion-schemes
- data-fix

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  lisp-format:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lisp-formatter

tests:
  lisp-formatter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lisp-formatter
    - hspec >= 2.10 && < 2.12
    - hspec-golden >= 0.2 && < 0.3
    - directory >= 1.3 && < 1.4
    - filepath >= 1.5 && < 1.6
